import math

#game consts
MAP_SIZE = (16, 16)

#player consts
SPEED = 0.003
ROTATION_SPEED = 0.00007
SHOOT_COOLDOWN = 0.7

MOUSE_BORDER = 200
MAX_MOUSE_REL = 40
COLISION_BOX_SIZE = 0.2
INIT_ANGLE = 0
INIT_POS = [2, 2]

#display consts
RESOLOTION = (1920, 1080)
FPS = 60

#engine consts
FOV = math.radians(90)
HALF_FOV = FOV/2
HALF_WIDTH = RESOLOTION[0] // 2
HALF_HEIGHT = RESOLOTION[1] // 2
TEXTURE_SIZE = 255
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
RAYS_NUM = RESOLOTION[0]//2
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = RESOLOTION[0]//RAYS_NUM
HALF_NUM_RAYS = RAYS_NUM // 2
DELTA_ANGLE = FOV / RAYS_NUM
RAY_MAX_STEPS = 20

#Animation consts
WALKIN_ANIMATION_INTERVAL = 0.15

#client consts
NOT_CONNECTED = "not connected"
WAITING_FOR_PLAYERS = "waiting for players"
IN_MATCH = "in match"
COMUNIOCATION_LOST = "comunication lost"